################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 04 : execution
####
################################################################

FILE = exec
include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
