################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 10 : thoughts on models for parallel computation
####
################################################################

FILE = models

include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
