################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 20 : mathematical basis of halo
####
################################################################

include ../../Make.inc
include ../Make.inc

FILE = halo

INEXDIR = "../.."
