################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 23 : distributed computing issues in IMP
####
################################################################

include ../../Make.inc
include ../Make.inc

FILE = distributed

INEXDIR = "../.."
