################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 22 : lulesh in IMP
####
################################################################

FILE = lulesh

include ../../Make.inc
include ../Make.inc

EXTRAEXTRATEXINPUTS = :../../graphics/lulesh

INEXDIR = "../.."

FILELONGNAME = IMP-22\ Lulesh
upload :: copy_to_source_repo
