################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 11 : a Gentle Introduction
####
################################################################

info ::
	@echo "make ${FILE}"

FILE = gentle

include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
PAGES = true

FILELONGNAME = IMP-11\ Gentle\ introduction
upload :: copy_to_source_repo
