################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 13 : sparse operations
####
################################################################

FILE = sparse
include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
