################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 21 : Adaptive mesh refinement
####
################################################################

include ../../Make.inc
include ../Make.inc

FILE = amr

INEXDIR = "../.."
