################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 18 : tutorial
####
################################################################

FILE = tutorial
include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."

upload :: copy_to_source_repo
