################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 25 : dense linear algebra
####
################################################################

include ../../Make.inc
include ../Make.inc

FILE = dense

INEXDIR = "../.."
