################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 09 : N-body problems
####
################################################################

FILE = nbody
include ../../Make.inc
include ../Make.inc
INEXDIR = ../..
