################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-7
####
#### 27 : big data
####
################################################################

include ../../Make.inc
include ../Make.inc

FILE = bigdata

INEXDIR = "../.."
