################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 26 : load balancing
####
################################################################

include ../../Make.inc
include ../Make.inc

FILE = load

INEXDIR = "../.."
