################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 24 : software-hardware codesign
####
################################################################

include ../../Make.inc
include ../Make.inc

FILE = codesign

INEXDIR = "../.."
