################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 20/arxiv : arxiv version of imp-20
####
################################################################

include ../../../Make.inc
include ../../Make.inc

FILE = arxiv-halo

INEXDIR = "../../.."
