################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 01 : distribution theory
####
################################################################

FILE = distribution

info ::
	@echo "make ${FILE}"

include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."

FILELONGNAME = IMP-01\ Distributions
upload :: copy_to_source_repo
