################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 08 : thoughts on resilience
####
################################################################

FILE = resil
include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
