################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 02 : deep theory of IMP
####
################################################################


FILE = deep

info ::
	@echo "make ${FILE}"

include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."


