# -*- makefile -*-
################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-9
####
#### 06 : communication avoiding
####
################################################################

FILE = avoid

include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
PAGES = true
##FILELONGNAME = IMP-06\ Communication\ avoiding
##upload :: copy_to_source_repo

clean ::
	@cd arxiv \
	&& make cleanfiles -f ../../../Make.inc
