################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 16 : local code theory
####
################################################################

include ../../Make.inc
include ../Make.inc
FILE = local
INEXDIR = "../.."
