################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 14 : all-pairs methods
####
################################################################

FILE = allpairs
include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
