################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 07 : on tagged sending
####
################################################################

FILE = tag

include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
