################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 19 : report on the NSF Eager project
####
################################################################

FILE = eager

include ../../Make.inc
include ../Make.inc

INEXDIR = "../.."

FILELONGNAME = IMP-19\ Eager\ report
upload :: copy_to_source_repo
