################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 12 : k-means averaging
####
################################################################

FILE = kmeans
include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
