################################################################
####
#### This makefile is part of the documentation of
#### the Integrative Model for Parallelism
####
#### copyright Victor Eijkhout 2014-6
####
#### 00 : the elevator pitch
####
################################################################

FILE = elevator

include ../../Make.inc
include ../Make.inc
INEXDIR = "../.."
